# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bank(object):
    def setupUi(self, bank):
        bank.setObjectName("bank")
        bank.resize(700, 420)
        self.tableWidget = QtWidgets.QTableWidget(bank)
        self.tableWidget.setGeometry(QtCore.QRect(90, 90, 520, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(bank)
        self.label.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_confirm = QtWidgets.QPushButton(bank)
        self.pushButton_confirm.setGeometry(QtCore.QRect(140, 320, 121, 41))
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.pushButton_refuse = QtWidgets.QPushButton(bank)
        self.pushButton_refuse.setGeometry(QtCore.QRect(420, 320, 121, 41))
        self.pushButton_refuse.setObjectName("pushButton_refuse")
        self.pushButton = QtWidgets.QPushButton(bank)
        self.pushButton.setGeometry(QtCore.QRect(520, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(bank)
        QtCore.QMetaObject.connectSlotsByName(bank)

    def retranslateUi(self, bank):
        _translate = QtCore.QCoreApplication.translate
        bank.setWindowTitle(_translate("bank", "bank"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("bank", "from"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("bank", "to"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("bank", "total_amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("bank", "cur_amount"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("bank", "deadline"))
        self.label.setText(_translate("bank", "receipt"))
        self.pushButton_confirm.setText(_translate("bank", "confirm"))
        self.pushButton_refuse.setText(_translate("bank", "refuse"))
        self.pushButton.setText(_translate("bank", "refresh"))
