# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'company.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_company(object):
    def setupUi(self, company):
        company.setObjectName("company")
        company.resize(700, 500)
        self.tableWidget = QtWidgets.QTableWidget(company)
        self.tableWidget.setGeometry(QtCore.QRect(90, 90, 520, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(company)
        self.label.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_sign = QtWidgets.QPushButton(company)
        self.pushButton_sign.setGeometry(QtCore.QRect(140, 320, 121, 41))
        self.pushButton_sign.setObjectName("pushButton_sign")
        self.pushButton_transfer = QtWidgets.QPushButton(company)
        self.pushButton_transfer.setGeometry(QtCore.QRect(420, 320, 121, 41))
        self.pushButton_transfer.setObjectName("pushButton_transfer")
        self.pushButton_finance = QtWidgets.QPushButton(company)
        self.pushButton_finance.setGeometry(QtCore.QRect(140, 410, 121, 41))
        self.pushButton_finance.setObjectName("pushButton_finance")
        self.pushButton_pay = QtWidgets.QPushButton(company)
        self.pushButton_pay.setGeometry(QtCore.QRect(420, 410, 121, 41))
        self.pushButton_pay.setObjectName("pushButton_pay")
        self.pushButton = QtWidgets.QPushButton(company)
        self.pushButton.setGeometry(QtCore.QRect(520, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(company)
        QtCore.QMetaObject.connectSlotsByName(company)

    def retranslateUi(self, company):
        _translate = QtCore.QCoreApplication.translate
        company.setWindowTitle(_translate("company", "company"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("company", "from"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("company", "to"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("company", "total_amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("company", "cur_amount"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("company", "deadline"))
        self.label.setText(_translate("company", "receipt"))
        self.pushButton_sign.setText(_translate("company", "sign"))
        self.pushButton_transfer.setText(_translate("company", "transfer"))
        self.pushButton_finance.setText(_translate("company", "finance"))
        self.pushButton_pay.setText(_translate("company", "pay"))
        self.pushButton.setText(_translate("company", "refresh"))