# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'company_sign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate


class Ui_company_sign(object):
    def setupUi(self, company_sign):
        company_sign.setObjectName("company_sign")
        company_sign.resize(700, 500)
        self.tableWidget = QtWidgets.QTableWidget(company_sign)
        self.tableWidget.setGeometry(QtCore.QRect(90, 90, 520, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(company_sign)
        self.label.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_to = QtWidgets.QLabel(company_sign)
        self.label_to.setGeometry(QtCore.QRect(270, 300, 21, 21))
        self.label_to.setObjectName("label_to")
        self.lineEdit_to = QtWidgets.QLineEdit(company_sign)
        self.lineEdit_to.setGeometry(QtCore.QRect(300, 300, 113, 21))
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.lineEdit_amount = QtWidgets.QLineEdit(company_sign)
        self.lineEdit_amount.setGeometry(QtCore.QRect(300, 350, 113, 21))
        self.lineEdit_amount.setObjectName("lineEdit_amount")
        self.label_amount = QtWidgets.QLabel(company_sign)
        self.label_amount.setGeometry(QtCore.QRect(240, 350, 51, 21))
        self.label_amount.setObjectName("label_amount")
        self.label_deadline = QtWidgets.QLabel(company_sign)
        self.label_deadline.setGeometry(QtCore.QRect(230, 400, 71, 21))
        self.label_deadline.setObjectName("label_deadline")
        self.dateEdit = QtWidgets.QDateEdit(company_sign)
        self.dateEdit.setGeometry(QtCore.QRect(300, 400, 116, 22))
        self.dateEdit.setDate(QDate.currentDate())
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_sign = QtWidgets.QPushButton(company_sign)
        self.pushButton_sign.setGeometry(QtCore.QRect(210, 440, 101, 31))
        self.pushButton_sign.setObjectName("pushButton_sign")
        self.pushButton_cancel = QtWidgets.QPushButton(company_sign)
        self.pushButton_cancel.setGeometry(QtCore.QRect(380, 440, 101, 31))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton = QtWidgets.QPushButton(company_sign)
        self.pushButton.setGeometry(QtCore.QRect(520, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(company_sign)
        QtCore.QMetaObject.connectSlotsByName(company_sign)

    def retranslateUi(self, company_sign):
        _translate = QtCore.QCoreApplication.translate
        company_sign.setWindowTitle(_translate("company_sign", "company_sign"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("company_sign", "from"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("company_sign", "to"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("company_sign", "total_amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("company_sign", "cur_amount"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("company_sign", "deadline"))
        self.label.setText(_translate("company_sign", "receipt"))
        self.label_to.setText(_translate("company_sign", "to"))
        self.label_amount.setText(_translate("company_sign", "amount"))
        self.label_deadline.setText(_translate("company_sign", "deadline"))
        self.pushButton_sign.setText(_translate("company_sign", "sign"))
        self.pushButton_cancel.setText(_translate("company_sign", "cancel"))
        self.pushButton.setText(_translate("company_sign", "refresh"))
