# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'company_finance.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate

class Ui_company_finance(object):
    def setupUi(self, company_finance):
        company_finance.setObjectName("company_finance")
        company_finance.resize(700, 500)
        self.tableWidget = QtWidgets.QTableWidget(company_finance)
        self.tableWidget.setGeometry(QtCore.QRect(90, 90, 520, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(company_finance)
        self.label.setGeometry(QtCore.QRect(290, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(company_finance)
        self.label_2.setGeometry(QtCore.QRect(210, 300, 121, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(company_finance)
        self.lineEdit.setGeometry(QtCore.QRect(330, 300, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(company_finance)
        self.label_3.setGeometry(QtCore.QRect(250, 340, 71, 21))
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(company_finance)
        self.dateEdit.setGeometry(QtCore.QRect(330, 340, 115, 22))
        self.dateEdit.setDate(QDate.currentDate())
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_apply = QtWidgets.QPushButton(company_finance)
        self.pushButton_apply.setGeometry(QtCore.QRect(220, 400, 93, 31))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.pushButton_cancel = QtWidgets.QPushButton(company_finance)
        self.pushButton_cancel.setGeometry(QtCore.QRect(410, 400, 93, 31))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton = QtWidgets.QPushButton(company_finance)
        self.pushButton.setGeometry(QtCore.QRect(520, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(company_finance)
        QtCore.QMetaObject.connectSlotsByName(company_finance)

    def retranslateUi(self, company_finance):
        _translate = QtCore.QCoreApplication.translate
        company_finance.setWindowTitle(_translate("company_finance", "company_finance"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("company_finance", "from"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("company_finance", "to"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("company_finance", "total_amount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("company_finance", "cur_amount"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("company_finance", "deadline"))
        self.label.setText(_translate("company_finance", "receipt"))
        self.label_2.setText(_translate("company_finance", "finance amount"))
        self.label_3.setText(_translate("company_finance", "deadline"))
        self.pushButton_apply.setText(_translate("company_finance", "apply"))
        self.pushButton_cancel.setText(_translate("company_finance", "cancel"))
        self.pushButton.setText(_translate("company_finance", "refresh"))
