# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(400, 300)
        self.pushButton_cancel = QtWidgets.QPushButton(signup)
        self.pushButton_cancel.setGeometry(QtCore.QRect(230, 200, 93, 28))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_signup = QtWidgets.QPushButton(signup)
        self.pushButton_signup.setGeometry(QtCore.QRect(90, 200, 93, 28))
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.lineEdit_name = QtWidgets.QLineEdit(signup)
        self.lineEdit_name.setGeometry(QtCore.QRect(180, 80, 113, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_pwd = QtWidgets.QLineEdit(signup)
        self.lineEdit_pwd.setGeometry(QtCore.QRect(180, 120, 113, 21))
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.label_name = QtWidgets.QLabel(signup)
        self.label_name.setGeometry(QtCore.QRect(110, 80, 72, 15))
        self.label_name.setObjectName("label_name")
        self.label_pwd = QtWidgets.QLabel(signup)
        self.label_pwd.setGeometry(QtCore.QRect(100, 120, 72, 15))
        self.label_pwd.setObjectName("label_pwd")

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "signup"))
        self.pushButton_cancel.setText(_translate("signup", "cancel"))
        self.pushButton_signup.setText(_translate("signup", "sign up"))
        self.label_name.setText(_translate("signup", "name"))
        self.label_pwd.setText(_translate("signup", "password"))
